num_folds: 5
n_gpu: 2
data_path: '/root/us_patent_matching/input'
model_path: microsoft/deberta-v3-large #roberta-large #xlm-roberta-large-finetuned-conll03-english # #anferico/bert-for-patents # # #

learning_rate: 0.00002
weight_decay: 0.01
epochs: 5
batch_size: 8 #32
max_len: 256
checkpoints: '/root/us_patent_matching/checkpoints'